# Ma_Don	
# Ngay_Dat	
# Ma_Khach_Hang	
# Ten_Khach_Hang	
# Gioi_Xung_Ho	
# So_Dien_Thoai	
# Tinh_Thanh	
# Phuong_Xa	
# Dia_Chi_Cu_The	
# Ma_San_Pham	
# Ten_San_Pham	
# Nhom_Hang	
# So_Luong	
# Don_Gia	
# Ty_Le_Giam_Gia	
# Tien_Giam	
# Tong_Hang	
# VAT_10	
# Phi_Van_Chuyen	
# Tong_Thanh_Toan	
# Don_Vi_Giao	
# Phuong_Thuc_Thanh_Toan	
# Kenh_Ban	
# Trang_Thai	
# Ngay_Giao_Du_Kien	
# So_Lan_Khach_Quay_Lai	
# thuong_hieu	
# danh_muc
